import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import Roboto instead of Inter
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import "./globals.css";

// Configure Roboto font with valid weights
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // Use "400" and "700" instead of "800"
});

export const metadata: Metadata = {
  title: "openPhone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply Roboto font globally by setting the className */}
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
